version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:          # <-- THIS IS CRITICAL
      - .env           # Injects your passwords and secrets into the container
    depends_on:
      - redis
      - mongodb