// Mock data — API fail hone par fallback ke liye use hoga
export const MOCK_JOBS = [
  {
    id: "job_001",
    _id: "job_001",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Remote",
    salary: "₹15-20 LPA",
    skills: ["React", "JavaScript", "CSS"],
    matchScore: 92,
    jobType: "remote",
    experienceLevel: "1-3 years",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    description: "We're looking for a passionate Frontend Developer to build beautiful, responsive web applications using React and modern CSS.",
    requirements: ["2+ years React experience", "Strong CSS/Tailwind skills", "REST API integration"],
    benefits: ["Remote work", "Health insurance", "Learning budget"],
    matchingSkills: ["React", "JavaScript", "CSS"],
    missingSkills: ["TypeScript"],
  },
  {
    id: "job_002",
    _id: "job_002",
    title: "Full Stack Engineer",
    company: "StartupHub",
    location: "Bangalore",
    salary: "₹18-25 LPA",
    skills: ["Node.js", "React", "MongoDB"],
    matchScore: 87,
    jobType: "fulltime",
    experienceLevel: "1-3 years",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    description: "Join our fast-growing startup to build scalable full-stack applications.",
    requirements: ["Node.js & React", "Database design", "Agile experience"],
    benefits: ["ESOP", "Flexible hours", "Team outings"],
    matchingSkills: ["React"],
    missingSkills: ["Node.js", "MongoDB"],
  },
  {
    id: "job_003",
    _id: "job_003",
    title: "UI/UX Designer",
    company: "DesignStudio",
    location: "Mumbai",
    salary: "₹12-16 LPA",
    skills: ["Figma", "UI Design", "Prototyping"],
    matchScore: 78,
    jobType: "fulltime",
    experienceLevel: "0-1 years",
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    description: "Create stunning user interfaces and delightful experiences for our clients.",
    requirements: ["Figma proficiency", "Portfolio required", "User research skills"],
    benefits: ["Creative freedom", "MacBook provided"],
    matchingSkills: ["UI Design"],
    missingSkills: ["Figma", "Prototyping"],
  },
  {
    id: "job_004",
    _id: "job_004",
    title: "Backend Developer",
    company: "CloudNine",
    location: "Hyderabad",
    salary: "₹20-28 LPA",
    skills: ["Python", "Django", "PostgreSQL"],
    matchScore: 85,
    jobType: "fulltime",
    experienceLevel: "3+ years",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    description: "Build robust backend systems and APIs for our cloud platform.",
    requirements: ["Python/Django expert", "PostgreSQL", "Microservices"],
    benefits: ["Work from home", "Annual bonus"],
    matchingSkills: ["Python"],
    missingSkills: ["Django", "PostgreSQL"],
  },
  {
    id: "job_005",
    _id: "job_005",
    title: "Data Analyst Intern",
    company: "DataWise",
    location: "Remote",
    salary: "₹25-35 K/month",
    skills: ["Python", "SQL", "Excel"],
    matchScore: 71,
    jobType: "internship",
    experienceLevel: "fresher",
    postedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    description: "Learn data analysis and visualization in a supportive team environment.",
    requirements: ["Basic Python", "SQL knowledge", "Currently pursuing degree"],
    benefits: ["Mentorship", "Certificate", "PPO opportunity"],
    matchingSkills: ["Python"],
    missingSkills: ["SQL"],
  },
  {
    id: "job_006",
    _id: "job_006",
    title: "DevOps Engineer",
    company: "InfraTech",
    location: "Pune",
    salary: "₹22-30 LPA",
    skills: ["AWS", "Docker", "Kubernetes"],
    matchScore: 68,
    jobType: "fulltime",
    experienceLevel: "3+ years",
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    description: "Manage cloud infrastructure and CI/CD pipelines for production systems.",
    requirements: ["AWS certified", "Docker/K8s", "Terraform"],
    benefits: ["Certification support", "Remote hybrid"],
    matchingSkills: ["Docker"],
    missingSkills: ["AWS", "Kubernetes"],
  },
];

export const MOCK_APPLICATIONS = [
  { id: "app_001", jobTitle: "Frontend Developer", company: "TechCorp", status: "interview", dateApplied: "2026-06-10", lastUpdate: "2026-06-18" },
  { id: "app_002", jobTitle: "Full Stack Engineer", company: "StartupHub", status: "applied", dateApplied: "2026-06-15", lastUpdate: "2026-06-15" },
  { id: "app_003", jobTitle: "Backend Developer", company: "CloudNine", status: "offer", dateApplied: "2026-06-01", lastUpdate: "2026-06-20" },
  { id: "app_004", jobTitle: "UI/UX Designer", company: "DesignStudio", status: "rejected", dateApplied: "2026-05-28", lastUpdate: "2026-06-05" },
  { id: "app_005", jobTitle: "DevOps Engineer", company: "InfraTech", status: "applied", dateApplied: "2026-06-12", lastUpdate: "2026-06-12" },
];

export const MOCK_NOTIFICATIONS = [
  { id: "n1", type: "application", title: "Interview Scheduled", description: "Interview scheduled for Frontend Developer at TechCorp", timestamp: new Date(Date.now() - 7200000).toISOString(), read: false },
  { id: "n2", type: "job", title: "New Job Matches", description: "Found 5 jobs matching your skills", timestamp: new Date(Date.now() - 86400000).toISOString(), read: false },
  { id: "n3", type: "resume", title: "Resume Analyzed", description: "Resume analyzed — 3 improvements suggested", timestamp: new Date(Date.now() - 172800000).toISOString(), read: true },
  { id: "n4", type: "coach", title: "Career Coach Reply", description: "Career Coach replied to your question", timestamp: new Date(Date.now() - 259200000).toISOString(), read: true },
  { id: "n5", type: "reminder", title: "Interview Reminder", description: "Interview in 2 days — Frontend Developer at TechCorp", timestamp: new Date(Date.now() - 345600000).toISOString(), read: false },
];

export const MOCK_TESTIMONIALS = [
  { id: 1, name: "Priya Sharma", role: "Software Engineer", company: "Google", quote: "JobReachAI's AI recommendations helped me find a perfect match in just 2 weeks!", rating: 5 },
  { id: 2, name: "Rahul Verma", role: "Product Manager", company: "Flipkart", quote: "The resume analyzer gave me actionable insights that landed me 3 interview calls.", rating: 5 },
  { id: 3, name: "Ananya Patel", role: "Data Scientist", company: "Amazon", quote: "Career Coach felt like having a mentor available 24/7. Highly recommend!", rating: 5 },
  { id: 4, name: "Arjun Singh", role: "Frontend Developer", company: "Swiggy", quote: "Skill gap analysis showed exactly what I needed to learn. Got hired within a month.", rating: 5 },
  { id: 5, name: "Sneha Reddy", role: "UX Designer", company: "Zomato", quote: "Application tracker kept me organized throughout my job search journey.", rating: 5 },
];

export const MOCK_CHAT_MESSAGES = [
  { id: 1, text: "Hi! I'm your AI Career Coach. How can I help you today?", isUser: false, timestamp: new Date(Date.now() - 3600000).toISOString() },
  { id: 2, text: "What skills should I focus on for frontend roles?", isUser: true, timestamp: new Date(Date.now() - 3500000).toISOString() },
  { id: 3, text: "Based on your profile, focus on React, TypeScript, and system design. These are in high demand for senior frontend roles. Would you like a learning path?", isUser: false, timestamp: new Date(Date.now() - 3400000).toISOString() },
];

export const DASHBOARD_STATS = {
  jobsApplied: 24,
  interviews: 8,
  matchScore: 87,
  profileCompletion: 95,
};

export const SKILL_RECOMMENDATIONS = [
  { id: 1, skill: "React", reason: "Required by 78% of your matched jobs" },
  { id: 2, skill: "TypeScript", reason: "Boost your match score by 12%" },
  { id: 3, skill: "System Design", reason: "Needed for senior-level positions" },
];
